modelling:
     finaldatapath: ../osppaa_data/
     resultspath: ./
     strong_trunc: 1
     mid_trunc: 2.5
     weak_trunc: 10
     low_mcap: 5000000
     low_vol: 50000
     high_mcap: 100000000 
     high_vol: 50000000
     mid_mcap: 10000000
     mid_vol: 1000000
