dataloading:
     min_mcap_threshold: 1000000
     min_vol_threshold: 25000
     min_rows_threshold: 100
     source_of_stablecoin_ids: cg_data_gen 
     price_var: prices
     vol_var: total_volumes
     na_cleaning_heads_and_tails_threshold: 2555
     na_cleaning_heads_and_tails_ignorecols: see_script 
     max_na_threshold: 100
     outlier_threshold_for_zscore: 5
     outlier_cols_to_be_treated: see_script
     path_to_save: ../02_raw_data/
     filename: inputdata_test
     volatility_sd_windowlength: 10
     volatility_sd_minobs: 3
     trend_longterm_windowlength: 31
     trend_longterm_periodization_multiplier: 31
     trend_longterm_ols_minobs: 20
     trend_shortterm_windowlength: 10
     trend_shortterm_scaling: 0.25
     trend_shortterm_minobs: 3
     fvalue_lineartrend_windowlength: 365
     fvalue_lineartrend_ols_minobs: 200
     fvalue_anchor_anchortyp: lma
     fvalue_anchor_wa_wlength: 365
     fvalue_anchor_minobs: 200
     fvalue_anchor_emwa_halflife: 150
     fvalue_choice_stabcoins: V_fact_fval_coll
     fvalue_choice_tradcoins: V_fvalue_emwa_30
     resistance_window_prd1_start: 63
     resistance_window_prd1_end: 16
     resistance_window_prd2_start: 15
     resistance_window_prd2_end: 10
     resistance_sensitivity: 0.85
     volume_windowlength: 10
     volume_scalingvar: 0.25     
     volume_minobs: 3     
     market_raw_data_dir: ../osppaa_2021_prepare_data/osppaa_raw_data

